# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: puppy
version: 1.0.0
config-version: 2

vars:
  quickbooks_database: RAW_DATA
  quickbooks_schema: QUICKBOOKS_3CFFAA8E9E5D11EC95D7ACDE48001122

  hubspot_database: RAW_DATA
  hubspot_schema: HUBSPOT_AA8E6EC69E5F11EC95D7ACDE48001122

  linkedin_pages_database: RAW_DATA
  linkedin_pages_schema: LINKEDIN_COMPANY_PAGES_91bbba4aa4a211ec80b5367dda3645bb

  linkedin_database: RAW_DATA
  linkedin_schema: LINKEDIN_ADS_E944A01E9E5E11EC95D7ACDE48001122

  #DISABLED MODELS
  #quickbooks
  using_sales_receipt: false
  #hubspot
  hubspot_email_event_enabled: false

# This setting configures which "profile" dbt uses for this project.
profile: undbt

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

target-path: target   # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
- target
- dbt_packages

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  undbt:
    +materialized: table
    un_quickbooks:
      +materialized: table
      +schema: QUICKBOOKS
      +database: ANALYTICS_DATA
    un_hubspot:
      +materialized: table
      +schema: HUBSPOT
      +database: ANALYTICS_DATA
    un_linkedin_pages:
      +materialized: table
      +schema: LINKEDIN_PAGES
      +database: ANALYTICS_DATA
puppy: evan
